services:
  web:
    build: .
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
      NODE_ENV: development
